project:
  type: website

website:
  title: "PeteMart"
  site-url: https://petem.art
  description: "A little family website by Peter and Marta."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css
